version: '3.8'

services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  pricing_engine:
    build: ./pricing_engine_rs
    ports:
      - "${RUST_API_PORT}:8080"
    environment:
      - RUST_API_PORT=${RUST_API_PORT}
    restart: always

  core_api:
    build: ./core_api_py
    ports:
      - "${PYTHON_API_PORT}:5000"
    depends_on:
      - mongo
      - pricing_engine
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - RUST_SERVICE_URL=http://pricing_engine:8080
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:27017/${MONGO_DB}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}

volumes:
  mongo_data:
